---
# Convert to json with: yq -o=json grant.yaml > grant.json
grants:
  - grant_id: 7/GRANT/2024
    alias: Grant Czekolada
    positions:
      - position_id: 1
        alias: Mikrokomputery
        budget: 637
      - position_id: 2
        alias: Materiały eksploatacyjne
        budget: 860
      - position_id: 3
        alias: Materiały konstrukcyjne
        budget: 5192.1
      - position_id: 4
        alias: Sensory
        budget: 140.4
      - position_id: 5
        alias: Lodówka
        budget: 700
      - position_id: 6
        alias: Części elektroniczne
        budget: 770.5
      - position_id: 7
        alias: Marketing
        budget: 1000
      - position_id: 8
        alias: Filament
        budget: 700
  - grant_id: 8/GRANT/2024
    alias: Grant Haptyka
    positions:
      - position_id: 1
        alias: Podzespoły elektroniczne
        budget: 9659
      - position_id: 2
        alias: Materiały eksploatacyjne do druku 3D
        budget: 2508
      - position_id: 3
        alias: Materiały warsztatowe
        budget: 2000
      - position_id: 4
        alias: Tekstylia
        budget: 500
      - position_id: 5
        alias: Materiały marketingowe
        budget: 500
      - position_id: 6
        alias: Materiały biurowe
        budget: 500
      - position_id: 7
        alias: Wyjazdy na konferencje
        budget: 2000
